config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  resources :coins
  get 'welcome_page/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome_page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end        
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [ :new, :create, :edit, :update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def locale
        I18n.locale == :en ? "Inglês" : "Português do Brasil"
    end
    
    def data_format(data_actual)
        I18n.locale == :en ? data_actual.strftime("%Y-%m-%d") : data_actual.strftime("%d-%m-%Y")
    end

    def ambiente_rails
        if Rails.env.development?
            "Desenvolvimento"
        elsif Rails.env.production?
            "Produção"
        else 
            "Teste"        
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p style="padding: 30px 0 10px 10px;">
    <strong> <%= t('description') %> </strong>
    <%= coin.description %>
  </p>

  <p style="padding: 30px 0 10px 10px;">
    <strong> <%= t('acronym') %> </strong>
    <%= coin.acronym %>
  </p>

  <p style="padding: 30px 0 10px 10px;"> 
    <strong> <%= t('url-image') %> </strong>
    <br>
    <%= image_tag coin.url_image, style: 'height:45px; width:45px;' %>
  </p>
</div>

app/views/coins/_footer.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "footer", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <footer>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-footer">
    </div>

    <div class="copyright">
      <p>
        ©2022<strong>Crypto Wallet</strong>. 
        <br>
        Todos os direitos reservados.
      </p> 
    </div>
  </footer>
</body>

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:"Bitcoin" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"BTC" %>
  </div>

  <div class="form-group">
    <%= form.label :url_image %>
    <%= form.text_field :url_image, class:"form-control", placeholder:"http://img.ur/bitcoin.png" %>
  </div>
  
  <div class="form-group">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blank: 'Selecione...' }, class:"form-control") %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-sm"  %>
  </div>
<% end %>

<br>

app/views/coins/_header.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "header", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <header>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-header">
    </div>

    <ul class="menu">
      <li><a href="/welcome_page/index"> <%= t('home-menu') %> </a></li>
      <li><a href="/coins"> <%= t('cois-menu') %> </a></li>
      <li><a href="/mining_types"> <%= t('mining-types-menu') %> </a></li>
      <li><a href="#"> <%= t('about-menu') %> </a></li>
      <li><a href="#"> <%= t('contact-menu') %> </a></li>
    </ul>

    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to "Português", root_path(locale: 'pt-BR'), class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "English", root_path(locale: 'en'), class:"nav-link" %>
      </li>
    </ul>
  </header>
</body>

app/views/coins/edit.html.erb
<div style="padding:10px;">
    <h1><%= t('edit-title.coin') %></h1>

    <%= render 'form', coin: @coin %>

    <%= link_to t('backing.coin'), coins_path, class:"btn btn-lg"  %>
</div>

app/views/coins/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Coins</title>
  <%= stylesheet_link_tag "coins", "data-turbo-track": "reload" %>
</head>
<body>
  <div class="container-coin">
    <main>
      <h1> <%= t('coin-title') %> </h1>
      <table class="table-one-coin">
        <thead>
          <tr>
            <th><p><%= @coins.human_attribute_name(:url_image) %></p></th>
            <th><p><%= @coins.human_attribute_name(:description) %></p></th>
            <th><p><%= @coins.human_attribute_name(:acronym) %></p></th>
            <th><p> <%= t('cotation-title') %> </p></th>
            <th><p> <%= t('value-title') %> </p></th>
          </tr>
        </thead>

        <tbody class="table-body-coin">
          <% @coins.each do |coin| %>
            <tr>
              <td><%= image_tag coin.url_image, style: 'height:45px; width:45px;' %></td>
              <td><%= coin.description %></td>
              <td><%= coin.acronym %></td>
              <td>R$100.000,00</td>
              <td>R$300.000,00</td>
              <td><%= link_to t('links.show'), coin, class:"btn btn-lg" %></td>
              <td><%= link_to t('links.edit'), edit_coin_path(coin), class:"btn btn-lg" %></td>
              <td><%= link_to t('links.delete'), coin, class:"btn btn-lg", method: :delete, data: { confirm: t('messages.confirm')} %></td>
            </tr>
          <% end %>
        </tbody>
        
        <div class="new-coin">
          <%= link_to t('new.coin'), new_coin_path, class:"btn btn-lg" %>
        </div>

      </table>
    </main>
  </div>
</body>
</html>

app/views/coins/new.html.erb
<div style="padding:10px;">
    <h1><%= t('new-title.coin') %></h1>

    <%= render 'form', coin: @coin %>

    <%= link_to t('backing.coin'), coins_path, class:"btn btn-lg" %>
</div>

app/views/coins/show.html.erb
<div style="padding:10px;">
  <p id="notice"><%= notice %></p>

  <form>

    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:description) %>
      <%= text_field_tag nil, @coin.description, class:"form-control", disabled: true %>
    </div>

    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:acronym) %>
      <%= text_field_tag nil, @coin.acronym, class:"form-control", disabled: true %>
    </div>

    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:url_image) %>
      <%= text_field_tag nil,@coin.url_image , class:"form-control", disabled: true %>
    </div>
    
    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:mining_type) %>
      <%= text_field_tag nil, @coin.mining_type.description , class:"form-control", disabled: true %>
    </div>
    
  </form>

  <%= link_to t('editing.coin'), edit_coin_path(@coin), class:"btn btn-lg" %> |
  <%= link_to t('backing.coin'), coins_path, class:"btn btn-lg" %>
</div>

app/views/layouts/_footer.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "footer", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <footer>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-footer">
    </div>

    <div class="copyright">
      <p>
        ©2022<strong>Crypto Wallet</strong>. 
        <br>
        Todos os direitos reservados.
      </p> 
    </div>
  </footer>
</body>

app/views/layouts/_header.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "header", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <header>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-header">
    </div>

    <ul class="menu">
      <li><a href="/welcome_page/index"> <%= t('home-menu') %> </a></li>
      <li><a href="/coins"> <%= t('cois-menu') %> </a></li>
      <li><a href="/mining_types"> <%= t('mining-types-menu') %> </a></li>
      <li><a href="#"> <%= t('about-menu') %> </a></li>
      <li><a href="#"> <%= t('contact-menu') %> </a></li>
    </ul>

    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to "Português", root_path(locale: 'pt-BR'), class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "English", root_path(locale: 'en'), class:"nav-link" %>
      </li>
    </ul>
  </header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Wallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag params[:controller], media: 'all', "data-turbolinks-track": "reload" %>

    <%= javascript_include_tag 'application', "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag params[:controller], "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "header" %>
      <%= yield %>
      <%= render "footer" %>
    </div>
  </body>
</html>

app/views/mining_types/_footer.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "footer", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <footer>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-footer">
    </div>

    <div class="copyright">
      <p>
        ©2022<strong>Crypto Wallet</strong>. 
        <br>
        Todos os direitos reservados.
      </p> 
    </div>
  </footer>
</body>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:"Proof of Work" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"PoW" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-sm" %>
  </div>
<% end %>
<br>

app/views/mining_types/_header.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "header", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <header>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-header">
    </div>

    <ul class="menu">
      <li><a href="/welcome_page/index"> <%= t('home-menu') %> </a></li>
      <li><a href="/coins"> <%= t('cois-menu') %> </a></li>
      <li><a href="/mining_types"> <%= t('mining-types-menu') %> </a></li>
      <li><a href="#"> <%= t('about-menu') %> </a></li>
      <li><a href="#"> <%= t('contact-menu') %> </a></li>
    </ul>

    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to "Português", root_path(locale: 'pt-BR'), class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "English", root_path(locale: 'en'), class:"nav-link" %>
      </li>
    </ul>
  </header>
</body>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p style="padding: 30px 0 10px 10px;">
    <strong> <%= t('description') %> </strong>
    <%= mining_type.description %>
  </p>

  <p style="padding: 30px 0 10px 10px;">
    <strong> <%= t('acronym') %> </strong>
    <%= mining_type.acronym %>
  </p>
</div>

app/views/mining_types/edit.html.erb
<div style="padding:10px;">
    <h1><%= t('edit-title.mining-type') %></h1>

    <%= render 'form', mining_type: @mining_type %>

    <%= link_to t('showing.mining-type'), @mining_type, class:"btn btn-lg" %> |
    <%= link_to t('backing.mining-type'), mining_types_path, class:"btn btn-lg" %>
</div>

app/views/mining_types/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mining Types</title>
    <%= stylesheet_link_tag "mining_types", "data-turbo-track": "reload" %>
</head>

<body>
  <div class="container-mining-types">
    <main>
      <h1> <%= t('mining-type-title') %> </h1>

      <div class="new-mining-types">
        <%= link_to t('new.mining-type'), new_mining_type_path, class:"btn btn-lg" %>
      </div>
      
      <div>
        <table class="table-one-mining-types">
          <thead>
            <tr>
              <th><p><%= @mining_types.human_attribute_name(:description) %></p></th>
              <th><p><%= @mining_types.human_attribute_name(:acronym) %></p></th>
            </tr>
          </thead>

          <tbody class="table-body-mining-types">
            <% @mining_types.each do |mining_type| %>
              <tr>
                <td><%= mining_type.description %></td>
                <td><%= mining_type.acronym %></td>
                <td><%= link_to t('links.show'), mining_type, class:"btn btn-lg" %></td>
                <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type), class:"btn btn-lg" %></td>
                <td><%= link_to t('links.delete'), mining_type, class:"btn btn-lg", method: :delete, data: { confirm: t('messages.confirm') } %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</body>
</html>

app/views/mining_types/new.html.erb
<div style="padding:10px;">    
    <h1><%= t('new-title.mining-type') %></h1>

    <%= render 'form', mining_type: @mining_type %>

    <%= link_to t('backing.mining-type'), mining_types_path, class:"btn btn-lg" %>
</div>   

app/views/mining_types/show.html.erb
<div style="padding:10px;">
  <p id="notice"><%= notice %></p>

  <form>

  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:description) %>
    <%= text_field_tag nil, @mining_type.description, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:acronym) %>
    <%= text_field_tag nil, @mining_type.acronym, class:"form-control", disabled: true %>
  </div>
    
  </form>

  <%= link_to t('editing.mining-type'), edit_mining_type_path(@mining_type), class:"btn btn-lg" %> |
  <%= link_to t('backing.mining-type'), mining_types_path, class:"btn btn-lg" %>
</div>

app/views/welcome_page/_footer.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "footer", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <footer>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-footer">
    </div>

    <div class="copyright">
      <p>
        ©2022<strong>Crypto Wallet</strong>. 
        <br>
        Todos os direitos reservados.
      </p> 
    </div>
  </footer>
</body>

app/views/welcome_page/_header.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "header", media: 'all', "data-turbolinks-track": "reload" %>
</head>

<body>
  <header>
    <div>
      <img src="<%= asset_path('crypto.png') %>" alt="Coin logo" class="logo-header">
    </div>

    <ul class="menu">
      <li><a href="/welcome_page/index"> <%= t('home-menu') %> </a></li>
      <li><a href="/coins"> <%= t('cois-menu') %> </a></li>
      <li><a href="/mining_types"> <%= t('mining-types-menu') %> </a></li>
      <li><a href="#"> <%= t('about-menu') %> </a></li>
      <li><a href="#"> <%= t('contact-menu') %> </a></li>
    </ul>

    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to "Português", root_path(locale: 'pt-BR'), class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "English", root_path(locale: 'en'), class:"nav-link" %>
      </li>
    </ul>
  </header>
</body>

app/views/welcome_page/_menu.html.erb
<%= link_to t('coins'), coins_path, class:"btn btn-lg", role:"button" %>
<%= link_to t('mining-type'), mining_types_path, class:"btn btn-lg", role:"button" %>

app/views/welcome_page/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Página Inicial</title>
  <%= stylesheet_link_tag "welcome_page", "data-turbo-track": "reload" %>
</head>

<body>
  <div class="jumbotron">
    <h1 class="display-4"><%= t('welcome') %></h1>
    <p class="lead"> <%= t('welcome-msg') %> </p>
    <hr class="my-4">
    <p> <%= t('menu-msg') %> </p>
    <%= render "menu" %>

    <hr> 

    <div class="main-content">
      <h1> <%= t('content-title') + "1" %> </h1>
      <p> lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      </p>
      <h1> <%= t('content-title') + "2" %> </h1>
      <p> lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      </p>
      <h1> <%= t('content-title') + "3" %> </h1>
      <p> lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
      </p>
    </div>

  </div>
</body>

</html>